name: Fetch EPG

on:
  schedule:
    # Runs daily at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # allows manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Fetch 7-day EPG
        run: node fetch_epg.js

      - name: Fetch 3-day EPG
        run: node fetch_full_epg.js

      - name: Commit EPG XML files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add epg_7day.xml epg_3day.xml
          git commit -m "Update EPG XML files"
          git push
