name: Fetch EPG

# Run every day at 3 AM UTC
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install axios iconv-lite epg-parser pako dayjs xmlbuilder

      # 4. Run EPG fetch script
      - name: Run fetch_epg.js
        run: node fetch_epg.js

      # 5. Commit and push XML files using PAT
      - name: Commit XML changes
        run: |
          git config user.name "EPG Bot"
          git config user.email "epgbot@example.com"
          git add *.xml
          git commit -m "Update EPG XML [skip ci]" || echo "No changes to commit"
          git push https://$GH_PAT@github.com/festy1986/epg-fetcher.git HEAD:main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
